// Deterministic scaffold for the `agent-node-tool-using` scaffold id.
//
// Each entry is a real, parseable file that ships verbatim into every
// generated agent project. The Forge's codegen layer MATERIALISES these
// files by copying — the LLM never touches them. The LLM-generated agent
// logic imports from this scaffold (tool library + runtime harness).
//
// IMPORTANT: This module is data only. It never executes the scaffold
// contents — that's the next layer's job (sandbox).

export interface ScaffoldFile {
  readonly path: string;
  readonly content: string;
}

// ----- file contents -------------------------------------------------------

const PACKAGE_JSON = `{
  "name": "forge-agent",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "tsc",
    "typecheck": "tsc --noEmit",
    "start": "tsx src/index.ts"
  },
  "dependencies": {
    "@anthropic-ai/sdk": "^0.40.0"
  },
  "devDependencies": {
    "@types/node": "^20.16.10",
    "tsx": "^4.19.1",
    "typescript": "^5.6.2"
  }
}
`;

const TSCONFIG_JSON = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true,
    "noUncheckedIndexedAccess": true,
    "outDir": "dist"
  },
  "include": ["src/**/*", "app/**/*"]
}
`;

const README_MD = `# forge-agent

This project was generated by **Aurexis Forge** from a confirmed AgentSpec
and an approved BuildPlan. The boilerplate, tool library, and runtime
harness are deterministic scaffold output. The agent-specific logic
(entrypoint + handlers) is LLM-generated.

## Layout

- \`src/lib/tools/\` — the tool library. Use these — don't reimplement.
- \`src/lib/runtime.ts\` — the agent runtime harness.
- Other files — generated agent logic and the entrypoint.

## Conventions

- ES modules; local imports use \`.js\` extensions.
- TypeScript strict mode is on.
- All secrets and provider URLs come from \`process.env\`.
`;

const TOOLS_TYPES_TS = `// Tool interface contract. Every tool in this directory implements this
// shape; generated agent logic invokes them via the typed \`call\` method.

export interface ToolContext {
  readonly env: NodeJS.ProcessEnv;
  readonly log: (message: string, meta?: Record<string, unknown>) => void;
}

export interface Tool<TInput = unknown, TOutput = unknown> {
  readonly id: string;
  readonly description: string;
  call(input: TInput, ctx: ToolContext): Promise<TOutput>;
}

export function requireEnv(ctx: ToolContext, key: string): string {
  const value = ctx.env[key];
  if (!value) {
    throw new Error(
      '[forge-agent] Required env var ' + key + ' is not set. ' +
        'Configure it before invoking this tool.',
    );
  }
  return value;
}

// Mock mode is set by the Forge sandbox during smoke tests. When on, every
// tool short-circuits to canned data without touching the network, disk,
// real LLM APIs, or any other side-effecting resource. This is the contract
// that lets the sandbox verify the agent runs without spending money or
// reaching real systems.
export function isMockMode(ctx: ToolContext): boolean {
  return ctx.env.FORGE_MOCK_TOOLS === '1';
}
`;

const TOOLS_INDEX_TS = `export type { Tool, ToolContext } from './types.js';
export { requireEnv, isMockMode } from './types.js';
export { web_search } from './web_search.js';
export { http_request } from './http_request.js';
export { llm_completion } from './llm_completion.js';
export { file_read } from './file_read.js';
export { file_write } from './file_write.js';
export { schedule } from './schedule.js';
export { email_read } from './email_read.js';
export { email_send } from './email_send.js';
`;

const TOOL_WEB_SEARCH_TS = `import type { Tool } from './types.js';
import { isMockMode } from './types.js';

export interface WebSearchInput {
  query: string;
  limit?: number;
}
export interface WebSearchResult {
  title: string;
  url: string;
  snippet: string;
}
export interface WebSearchOutput {
  results: WebSearchResult[];
}

// Lightweight HTTP-based web search. Configure WEB_SEARCH_URL to point at a
// JSON-returning search endpoint that accepts a \`q\` query parameter and
// returns { results: WebSearchResult[] }. With no endpoint configured the
// tool resolves to an empty result list rather than failing — generated
// agents should handle that case.
export const web_search: Tool<WebSearchInput, WebSearchOutput> = {
  id: 'web_search',
  description: 'Search the public web. Configure WEB_SEARCH_URL.',
  async call({ query, limit }, ctx) {
    if (isMockMode(ctx)) {
      ctx.log('web_search.mock', { query, limit });
      return {
        results: [
          {
            title: 'Mock result for: ' + query,
            url: 'https://example.com/mock',
            snippet: 'Mocked snippet — no real network call was made.',
          },
        ],
      };
    }
    const endpoint = ctx.env.WEB_SEARCH_URL;
    ctx.log('web_search', { query, limit });
    if (!endpoint) {
      return { results: [] };
    }
    const url = new URL(endpoint);
    url.searchParams.set('q', query);
    if (limit != null) url.searchParams.set('limit', String(limit));
    const res = await fetch(url, { headers: { accept: 'application/json' } });
    if (!res.ok) {
      throw new Error('web_search HTTP ' + res.status);
    }
    const data = (await res.json()) as WebSearchOutput;
    return data;
  },
};
`;

const TOOL_HTTP_REQUEST_TS = `import type { Tool } from './types.js';
import { isMockMode } from './types.js';

export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';

export interface HttpRequestInput {
  url: string;
  method?: HttpMethod;
  headers?: Record<string, string>;
  body?: string | Record<string, unknown>;
}
export interface HttpRequestOutput {
  status: number;
  ok: boolean;
  headers: Record<string, string>;
  body: string;
}

export const http_request: Tool<HttpRequestInput, HttpRequestOutput> = {
  id: 'http_request',
  description: 'Make an arbitrary HTTP request and return the response.',
  async call(input, ctx) {
    if (isMockMode(ctx)) {
      ctx.log('http_request.mock', { url: input.url, method: input.method });
      return {
        status: 200,
        ok: true,
        headers: { 'content-type': 'application/json' },
        body: '{"mocked": true}',
      };
    }
    const method: HttpMethod = input.method ?? 'GET';
    const headers: Record<string, string> = { ...(input.headers ?? {}) };
    let body: BodyInit | undefined;
    if (input.body != null) {
      if (typeof input.body === 'string') {
        body = input.body;
      } else {
        body = JSON.stringify(input.body);
        if (!headers['content-type'] && !headers['Content-Type']) {
          headers['content-type'] = 'application/json';
        }
      }
    }
    ctx.log('http_request', { method, url: input.url });
    const res = await fetch(input.url, { method, headers, body });
    const text = await res.text();
    const resHeaders: Record<string, string> = {};
    res.headers.forEach((v, k) => {
      resHeaders[k] = v;
    });
    return { status: res.status, ok: res.ok, headers: resHeaders, body: text };
  },
};
`;

const TOOL_LLM_COMPLETION_TS = `import Anthropic from '@anthropic-ai/sdk';
import type { Tool } from './types.js';
import { isMockMode, requireEnv } from './types.js';

export interface LlmCompletionInput {
  user: string;
  system?: string;
  model?: string;
  maxTokens?: number;
}
export interface LlmCompletionOutput {
  text: string;
  input_tokens: number;
  output_tokens: number;
  model: string;
}

let client: Anthropic | null = null;
function getClient(apiKey: string): Anthropic {
  if (!client) client = new Anthropic({ apiKey });
  return client;
}

export const llm_completion: Tool<LlmCompletionInput, LlmCompletionOutput> = {
  id: 'llm_completion',
  description: 'Run a single Anthropic LLM completion.',
  async call(input, ctx) {
    if (isMockMode(ctx)) {
      ctx.log('llm_completion.mock', { prompt_chars: input.user.length });
      return {
        text: 'Mock LLM response (sandbox smoke test — no real API call).',
        input_tokens: 0,
        output_tokens: 0,
        model: 'mock',
      };
    }
    const apiKey = requireEnv(ctx, 'ANTHROPIC_API_KEY');
    const c = getClient(apiKey);
    const model = input.model ?? ctx.env.AGENT_LLM_MODEL ?? 'claude-sonnet-4-6';
    const max_tokens = input.maxTokens ?? 2048;
    ctx.log('llm_completion', { model, max_tokens });
    const resp = await c.messages.create({
      model,
      max_tokens,
      ...(input.system ? { system: input.system } : {}),
      messages: [{ role: 'user', content: input.user }],
    });
    const text = resp.content
      .map((b) => (b.type === 'text' ? b.text : ''))
      .join('');
    return {
      text,
      input_tokens: resp.usage.input_tokens,
      output_tokens: resp.usage.output_tokens,
      model: resp.model,
    };
  },
};
`;

const TOOL_FILE_READ_TS = `import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { Tool } from './types.js';
import { isMockMode } from './types.js';

export interface FileReadInput {
  path: string;
}
export interface FileReadOutput {
  path: string;
  content: string;
  bytes: number;
}

function workspaceRoot(env: NodeJS.ProcessEnv): string {
  return resolve(env.AGENT_WORKSPACE ?? process.cwd());
}

export const file_read: Tool<FileReadInput, FileReadOutput> = {
  id: 'file_read',
  description: 'Read a UTF-8 text file from the agent workspace.',
  async call({ path }, ctx) {
    if (isMockMode(ctx)) {
      ctx.log('file_read.mock', { path });
      return { path, content: 'mock file contents', bytes: 19 };
    }
    const root = workspaceRoot(ctx.env);
    const full = resolve(root, path);
    if (!full.startsWith(root)) {
      throw new Error('[forge-agent] file_read path escapes workspace');
    }
    ctx.log('file_read', { path });
    const content = await readFile(full, 'utf8');
    return { path, content, bytes: Buffer.byteLength(content, 'utf8') };
  },
};
`;

const TOOL_FILE_WRITE_TS = `import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import type { Tool } from './types.js';
import { isMockMode } from './types.js';

export interface FileWriteInput {
  path: string;
  content: string;
}
export interface FileWriteOutput {
  path: string;
  bytes: number;
}

function workspaceRoot(env: NodeJS.ProcessEnv): string {
  return resolve(env.AGENT_WORKSPACE ?? process.cwd());
}

export const file_write: Tool<FileWriteInput, FileWriteOutput> = {
  id: 'file_write',
  description: 'Write a UTF-8 text file to the agent workspace.',
  async call({ path, content }, ctx) {
    if (isMockMode(ctx)) {
      ctx.log('file_write.mock', { path, bytes: content.length });
      return { path, bytes: content.length };
    }
    const root = workspaceRoot(ctx.env);
    const full = resolve(root, path);
    if (!full.startsWith(root)) {
      throw new Error('[forge-agent] file_write path escapes workspace');
    }
    ctx.log('file_write', { path, bytes: content.length });
    await mkdir(dirname(full), { recursive: true });
    await writeFile(full, content, 'utf8');
    return { path, bytes: Buffer.byteLength(content, 'utf8') };
  },
};
`;

const TOOL_SCHEDULE_TS = `import type { Tool } from './types.js';
import { isMockMode } from './types.js';

// The schedule tool declares an intended cron expression. The hosting
// environment is responsible for actually installing the schedule (Vercel
// Cron, Cloudflare Cron Triggers, etc.). Calling this tool at runtime is
// effectively a no-op that returns the declaration for logging.

export interface ScheduleInput {
  cron: string;
}
export interface ScheduleOutput {
  cron: string;
  declared_at: string;
}

export const schedule: Tool<ScheduleInput, ScheduleOutput> = {
  id: 'schedule',
  description: 'Declare the cron schedule the hosting environment should install.',
  async call({ cron }, ctx) {
    if (!cron || typeof cron !== 'string') {
      throw new Error('[forge-agent] schedule.cron must be a non-empty string');
    }
    if (isMockMode(ctx)) {
      ctx.log('schedule.mock', { cron });
      return { cron, declared_at: new Date(0).toISOString() };
    }
    ctx.log('schedule', { cron });
    return { cron, declared_at: new Date().toISOString() };
  },
};
`;

const TOOL_EMAIL_READ_TS = `import type { Tool } from './types.js';
import { isMockMode, requireEnv } from './types.js';

// STUB — needs_key. Reads GMAIL_OAUTH_TOKEN and fails clearly if unset.
// Replace the body with a real Gmail API fetch when wiring up the
// integration.

export interface EmailReadInput {
  query?: string;
  limit?: number;
}
export interface EmailMessage {
  id: string;
  from: string;
  subject: string;
  body: string;
  received_at: string;
}
export interface EmailReadOutput {
  messages: EmailMessage[];
}

export const email_read: Tool<EmailReadInput, EmailReadOutput> = {
  id: 'email_read',
  description: 'Read recent emails from a connected Gmail mailbox.',
  async call(_input, ctx) {
    if (isMockMode(ctx)) {
      ctx.log('email_read.mock', {});
      return { messages: [] };
    }
    requireEnv(ctx, 'GMAIL_OAUTH_TOKEN');
    throw new Error(
      '[forge-agent] email_read is not yet wired up in this scaffold. ' +
        'Implement Gmail API fetch using GMAIL_OAUTH_TOKEN here.',
    );
  },
};
`;

const TOOL_EMAIL_SEND_TS = `import type { Tool } from './types.js';
import { isMockMode, requireEnv } from './types.js';

// STUB — needs_key. Reads RESEND_API_KEY and fails clearly if unset.
// Replace the body with a real Resend (or other) send-email call when
// wiring up the integration.

export interface EmailSendInput {
  to: string | string[];
  subject: string;
  body: string;
  from?: string;
}
export interface EmailSendOutput {
  message_id: string;
  sent_at: string;
}

export const email_send: Tool<EmailSendInput, EmailSendOutput> = {
  id: 'email_send',
  description: 'Send an email via Resend.',
  async call(input, ctx) {
    if (isMockMode(ctx)) {
      ctx.log('email_send.mock', { to: input.to, subject: input.subject });
      return { message_id: 'mock-' + Date.now(), sent_at: new Date(0).toISOString() };
    }
    requireEnv(ctx, 'RESEND_API_KEY');
    throw new Error(
      '[forge-agent] email_send is not yet wired up in this scaffold. ' +
        'Implement Resend send-email using RESEND_API_KEY here.',
    );
  },
};
`;

const RUNTIME_TS = `import type { ToolContext } from './tools/types.js';

export type Trigger = 'chat' | 'api' | 'schedule' | 'webhook';

export interface AgentHandler<I, O> {
  (input: I, ctx: ToolContext): Promise<O>;
}

export interface AgentDefinition<I, O> {
  trigger: Trigger;
  handler: AgentHandler<I, O>;
}

export function defineAgent<I, O>(def: AgentDefinition<I, O>): AgentDefinition<I, O> {
  return def;
}

export function createContext(overrides?: Partial<ToolContext>): ToolContext {
  return {
    env: process.env,
    log: (message, meta) => {
      const suffix = meta ? ' ' + JSON.stringify(meta) : '';
      console.log('[agent] ' + message + suffix);
    },
    ...(overrides ?? {}),
  };
}

// One-shot invocation. The entrypoint composes this with a trigger.
export async function runOnce<I, O>(
  agent: AgentDefinition<I, O>,
  input: I,
): Promise<O> {
  return agent.handler(input, createContext());
}

// HTTP API trigger. Returns a fetch-style handler (req → res).
export function asApiHandler<I, O>(agent: AgentDefinition<I, O>) {
  return async (req: Request): Promise<Response> => {
    try {
      const input = (await req.json()) as I;
      const result = await runOnce(agent, input);
      return new Response(JSON.stringify({ ok: true, result }), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : 'unknown error';
      return new Response(JSON.stringify({ ok: false, error: message }), {
        status: 500,
        headers: { 'content-type': 'application/json' },
      });
    }
  };
}

// Webhook trigger. Same shape as the API trigger, with an optional
// signature-verification hook.
export function asWebhookHandler<I, O>(
  agent: AgentDefinition<I, O>,
  options?: { verify?: (req: Request) => Promise<boolean> },
) {
  const inner = asApiHandler(agent);
  return async (req: Request): Promise<Response> => {
    if (options?.verify) {
      const ok = await options.verify(req);
      if (!ok) return new Response('forbidden', { status: 403 });
    }
    return inner(req);
  };
}

// CLI / chat trigger. Reads stdin to a string, parses, runs once.
export async function runChatStdin<I, O>(
  agent: AgentDefinition<I, O>,
  parse: (raw: string) => I,
): Promise<O> {
  process.stdin.setEncoding('utf8');
  const chunks: string[] = [];
  for await (const chunk of process.stdin) {
    chunks.push(String(chunk));
  }
  const raw = chunks.join('').trim();
  return runOnce(agent, parse(raw));
}
`;

// ----- export --------------------------------------------------------------

export const SCAFFOLD_FILES: readonly ScaffoldFile[] = [
  { path: 'package.json', content: PACKAGE_JSON },
  { path: 'tsconfig.json', content: TSCONFIG_JSON },
  { path: 'README.md', content: README_MD },
  { path: 'src/lib/tools/types.ts', content: TOOLS_TYPES_TS },
  { path: 'src/lib/tools/index.ts', content: TOOLS_INDEX_TS },
  { path: 'src/lib/tools/web_search.ts', content: TOOL_WEB_SEARCH_TS },
  { path: 'src/lib/tools/http_request.ts', content: TOOL_HTTP_REQUEST_TS },
  { path: 'src/lib/tools/llm_completion.ts', content: TOOL_LLM_COMPLETION_TS },
  { path: 'src/lib/tools/file_read.ts', content: TOOL_FILE_READ_TS },
  { path: 'src/lib/tools/file_write.ts', content: TOOL_FILE_WRITE_TS },
  { path: 'src/lib/tools/schedule.ts', content: TOOL_SCHEDULE_TS },
  { path: 'src/lib/tools/email_read.ts', content: TOOL_EMAIL_READ_TS },
  { path: 'src/lib/tools/email_send.ts', content: TOOL_EMAIL_SEND_TS },
  { path: 'src/lib/runtime.ts', content: RUNTIME_TS },
];

// Summary the LLM consumes when generating agent files. Distilled from the
// full scaffold so the prompt stays compact while still pinning down the
// interface the model must use.
export const SCAFFOLD_TOOL_INTERFACE = `// src/lib/tools/types.ts
export interface ToolContext {
  readonly env: NodeJS.ProcessEnv;
  readonly log: (message: string, meta?: Record<string, unknown>) => void;
}
export interface Tool<TInput, TOutput> {
  readonly id: string;
  readonly description: string;
  call(input: TInput, ctx: ToolContext): Promise<TOutput>;
}
export function requireEnv(ctx: ToolContext, key: string): string;
export function isMockMode(ctx: ToolContext): boolean; // returns ctx.env.FORGE_MOCK_TOOLS === '1' — tools self-mock for sandbox smoke tests

// src/lib/tools/index.ts — every exported tool
export const web_search:     Tool<{ query: string; limit?: number }, { results: { title: string; url: string; snippet: string }[] }>;
export const http_request:   Tool<{ url: string; method?: 'GET'|'POST'|'PUT'|'PATCH'|'DELETE'; headers?: Record<string,string>; body?: string|Record<string, unknown> }, { status: number; ok: boolean; headers: Record<string,string>; body: string }>;
export const llm_completion: Tool<{ user: string; system?: string; model?: string; maxTokens?: number }, { text: string; input_tokens: number; output_tokens: number; model: string }>;
export const file_read:      Tool<{ path: string }, { path: string; content: string; bytes: number }>;
export const file_write:     Tool<{ path: string; content: string }, { path: string; bytes: number }>;
export const schedule:       Tool<{ cron: string }, { cron: string; declared_at: string }>;
export const email_read:     Tool<{ query?: string; limit?: number }, { messages: { id: string; from: string; subject: string; body: string; received_at: string }[] }>;  // needs_key: GMAIL_OAUTH_TOKEN
export const email_send:     Tool<{ to: string|string[]; subject: string; body: string; from?: string }, { message_id: string; sent_at: string }>;                       // needs_key: RESEND_API_KEY

// src/lib/runtime.ts
export type Trigger = 'chat' | 'api' | 'schedule' | 'webhook';
export interface AgentHandler<I, O> { (input: I, ctx: ToolContext): Promise<O>; }
export interface AgentDefinition<I, O> { trigger: Trigger; handler: AgentHandler<I, O>; }
export function defineAgent<I, O>(def: AgentDefinition<I, O>): AgentDefinition<I, O>;
export function createContext(overrides?: Partial<ToolContext>): ToolContext;
export function runOnce<I, O>(agent: AgentDefinition<I, O>, input: I): Promise<O>;
export function asApiHandler<I, O>(agent: AgentDefinition<I, O>): (req: Request) => Promise<Response>;
export function asWebhookHandler<I, O>(agent: AgentDefinition<I, O>, options?: { verify?: (req: Request) => Promise<boolean> }): (req: Request) => Promise<Response>;
export function runChatStdin<I, O>(agent: AgentDefinition<I, O>, parse: (raw: string) => I): Promise<O>;
`;
