// Deterministic scaffold for the `agent-node-tool-using` scaffold id.
//
// Each entry is a real, parseable file that ships verbatim into every
// generated agent project. The Forge's codegen layer MATERIALISES these
// files by copying — the LLM never touches them. The LLM-generated agent
// logic imports from this scaffold (tool library + runtime harness).
//
// SOURCE-OF-TRUTH CHANGE (tool-contract migration): the per-tool source
// files (src/lib/tools/<name>.ts), the tool barrel (index.ts), and the
// compact SCAFFOLD_TOOL_INTERFACE are now DERIVED from the engine tool
// contract (lib/engine/tools/builtin). The boilerplate files
// (package.json, tsconfig, README, types.ts, runtime.ts) remain fixed
// here. Adding/removing a builtin tool flows through automatically while
// the shipped output for the existing 8 tools stays byte-identical.
//
// IMPORTANT: This module is data only. It never executes the scaffold
// contents — that's the next layer's job (sandbox).

import { PLANNER_TOOLS } from '../../tools/builtin';

export interface ScaffoldFile {
  readonly path: string;
  readonly content: string;
}

// ----- fixed boilerplate file contents -------------------------------------

const PACKAGE_JSON = `{
  "name": "forge-agent",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "tsc",
    "typecheck": "tsc --noEmit",
    "start": "tsx src/index.ts"
  },
  "dependencies": {
    "@anthropic-ai/sdk": "^0.40.0"
  },
  "devDependencies": {
    "@types/node": "^20.16.10",
    "tsx": "^4.19.1",
    "typescript": "^5.6.2"
  }
}
`;

const TSCONFIG_JSON = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true,
    "noUncheckedIndexedAccess": true,
    "outDir": "dist"
  },
  "include": ["src/**/*", "app/**/*"]
}
`;

const README_MD = `# forge-agent

This project was generated by **Aurexis Forge** from a confirmed AgentSpec
and an approved BuildPlan. The boilerplate, tool library, and runtime
harness are deterministic scaffold output. The agent-specific logic
(entrypoint + handlers) is LLM-generated.

## Layout

- \`src/lib/tools/\` — the tool library. Use these — don't reimplement.
- \`src/lib/runtime.ts\` — the agent runtime harness.
- Other files — generated agent logic and the entrypoint.

## Conventions

- ES modules; local imports use \`.js\` extensions.
- TypeScript strict mode is on.
- All secrets and provider URLs come from \`process.env\`.
`;

const TOOLS_TYPES_TS = `// Tool interface contract. Every tool in this directory implements this
// shape; generated agent logic invokes them via the typed \`call\` method.

export interface ToolContext {
  readonly env: NodeJS.ProcessEnv;
  readonly log: (message: string, meta?: Record<string, unknown>) => void;
}

export interface Tool<TInput = unknown, TOutput = unknown> {
  readonly id: string;
  readonly description: string;
  call(input: TInput, ctx: ToolContext): Promise<TOutput>;
}

export function requireEnv(ctx: ToolContext, key: string): string {
  const value = ctx.env[key];
  if (!value) {
    throw new Error(
      '[forge-agent] Required env var ' + key + ' is not set. ' +
        'Configure it before invoking this tool.',
    );
  }
  return value;
}

// Mock mode is set by the Forge sandbox during smoke tests. When on, every
// tool short-circuits to canned data without touching the network, disk,
// real LLM APIs, or any other side-effecting resource. This is the contract
// that lets the sandbox verify the agent runs without spending money or
// reaching real systems.
export function isMockMode(ctx: ToolContext): boolean {
  return ctx.env.FORGE_MOCK_TOOLS === '1';
}
`;

const RUNTIME_TS = `import type { ToolContext } from './tools/types.js';

export type Trigger = 'chat' | 'api' | 'schedule' | 'webhook';

export interface AgentHandler<I, O> {
  (input: I, ctx: ToolContext): Promise<O>;
}

export interface AgentDefinition<I, O> {
  trigger: Trigger;
  handler: AgentHandler<I, O>;
}

export function defineAgent<I, O>(def: AgentDefinition<I, O>): AgentDefinition<I, O> {
  return def;
}

export function createContext(overrides?: Partial<ToolContext>): ToolContext {
  return {
    env: process.env,
    log: (message, meta) => {
      const suffix = meta ? ' ' + JSON.stringify(meta) : '';
      console.log('[agent] ' + message + suffix);
    },
    ...(overrides ?? {}),
  };
}

// One-shot invocation. The entrypoint composes this with a trigger.
export async function runOnce<I, O>(
  agent: AgentDefinition<I, O>,
  input: I,
): Promise<O> {
  return agent.handler(input, createContext());
}

// HTTP API trigger. Returns a fetch-style handler (req → res).
export function asApiHandler<I, O>(agent: AgentDefinition<I, O>) {
  return async (req: Request): Promise<Response> => {
    try {
      const input = (await req.json()) as I;
      const result = await runOnce(agent, input);
      return new Response(JSON.stringify({ ok: true, result }), {
        status: 200,
        headers: { 'content-type': 'application/json' },
      });
    } catch (err) {
      const message = err instanceof Error ? err.message : 'unknown error';
      return new Response(JSON.stringify({ ok: false, error: message }), {
        status: 500,
        headers: { 'content-type': 'application/json' },
      });
    }
  };
}

// Webhook trigger. Same shape as the API trigger, with an optional
// signature-verification hook.
export function asWebhookHandler<I, O>(
  agent: AgentDefinition<I, O>,
  options?: { verify?: (req: Request) => Promise<boolean> },
) {
  const inner = asApiHandler(agent);
  return async (req: Request): Promise<Response> => {
    if (options?.verify) {
      const ok = await options.verify(req);
      if (!ok) return new Response('forbidden', { status: 403 });
    }
    return inner(req);
  };
}

// CLI / chat trigger. Reads stdin to a string, parses, runs once.
export async function runChatStdin<I, O>(
  agent: AgentDefinition<I, O>,
  parse: (raw: string) => I,
): Promise<O> {
  process.stdin.setEncoding('utf8');
  const chunks: string[] = [];
  for await (const chunk of process.stdin) {
    chunks.push(String(chunk));
  }
  const raw = chunks.join('').trim();
  return runOnce(agent, parse(raw));
}
`;

// ----- derived tool barrel (index.ts) --------------------------------------
// Header (type + helper re-exports) is fixed; the per-tool export lines are
// derived from the contract tools in canonical order.

const TOOLS_INDEX_HEADER = `export type { Tool, ToolContext } from './types.js';
export { requireEnv, isMockMode } from './types.js';
`;

const TOOLS_INDEX_TS =
  TOOLS_INDEX_HEADER +
  PLANNER_TOOLS.map((t) => "export { " + t.name + " } from './" + t.name + ".js';\n").join('');

// ----- export --------------------------------------------------------------
// SCAFFOLD_FILES = fixed boilerplate + one file per contract tool (its
// scaffoldSource) at src/lib/tools/<name>.ts, in canonical order.

export const SCAFFOLD_FILES: readonly ScaffoldFile[] = [
  { path: 'package.json', content: PACKAGE_JSON },
  { path: 'tsconfig.json', content: TSCONFIG_JSON },
  { path: 'README.md', content: README_MD },
  { path: 'src/lib/tools/types.ts', content: TOOLS_TYPES_TS },
  { path: 'src/lib/tools/index.ts', content: TOOLS_INDEX_TS },
  ...PLANNER_TOOLS.map((t) => ({
    path: 'src/lib/tools/' + t.name + '.ts',
    content: t.scaffoldSource,
  })),
  { path: 'src/lib/runtime.ts', content: RUNTIME_TS },
];

// Summary the LLM consumes when generating agent files. Distilled from the
// full scaffold so the prompt stays compact while still pinning down the
// interface the model must use. Header + footer are fixed; the per-tool
// signature lines are derived from the contract (carried verbatim).

const SCAFFOLD_INTERFACE_HEADER = `// src/lib/tools/types.ts
export interface ToolContext {
  readonly env: NodeJS.ProcessEnv;
  readonly log: (message: string, meta?: Record<string, unknown>) => void;
}
export interface Tool<TInput, TOutput> {
  readonly id: string;
  readonly description: string;
  call(input: TInput, ctx: ToolContext): Promise<TOutput>;
}
export function requireEnv(ctx: ToolContext, key: string): string;
export function isMockMode(ctx: ToolContext): boolean; // returns ctx.env.FORGE_MOCK_TOOLS === '1' — tools self-mock for sandbox smoke tests

// src/lib/tools/index.ts — every exported tool
`;

const SCAFFOLD_INTERFACE_FOOTER = `// src/lib/runtime.ts
export type Trigger = 'chat' | 'api' | 'schedule' | 'webhook';
export interface AgentHandler<I, O> { (input: I, ctx: ToolContext): Promise<O>; }
export interface AgentDefinition<I, O> { trigger: Trigger; handler: AgentHandler<I, O>; }
export function defineAgent<I, O>(def: AgentDefinition<I, O>): AgentDefinition<I, O>;
export function createContext(overrides?: Partial<ToolContext>): ToolContext;
export function runOnce<I, O>(agent: AgentDefinition<I, O>, input: I): Promise<O>;
export function asApiHandler<I, O>(agent: AgentDefinition<I, O>): (req: Request) => Promise<Response>;
export function asWebhookHandler<I, O>(agent: AgentDefinition<I, O>, options?: { verify?: (req: Request) => Promise<boolean> }): (req: Request) => Promise<Response>;
export function runChatStdin<I, O>(agent: AgentDefinition<I, O>, parse: (raw: string) => I): Promise<O>;
`;

export const SCAFFOLD_TOOL_INTERFACE =
  SCAFFOLD_INTERFACE_HEADER +
  PLANNER_TOOLS.map((t) => t.scaffoldInterfaceSignature + '\n').join('') +
  '\n' +
  SCAFFOLD_INTERFACE_FOOTER;
