// Smoke-test driver synthesis.
//
// The runner writes one extra file into the sandbox — `forge_smoke.mjs` —
// that loads the agent module and invokes it with a synthetic safe input
// appropriate to the spec's trigger. Mock-mode tools handle the actual
// side-effects, so no real network call ever happens.

import type { BuildPlan } from '../planner/schema';
import type { AgentSpec } from '../spec/schema';

export interface SmokePlan {
  // The contents of forge_smoke.mjs to write into the sandbox.
  driverContent: string;
  // The command to run for the smoke phase.
  command: string;
  // Stdin to feed to the smoke process, if any.
  stdin?: string;
  // Max wall-clock for the smoke process.
  timeoutMs: number;
  // Whether a timeout should be treated as a soft pass (server-like
  // triggers that don't exit on their own).
  softTimeout: boolean;
}

const SYNTHETIC_INPUTS: Record<AgentSpec['trigger'], string> = {
  chat: 'Hello — this is the Aurexis Forge sandbox smoke test. Please confirm you are alive.',
  api: '{"forge_smoke": true, "message": "ping"}',
  schedule: '{"forge_smoke": true, "scheduled_at": "1970-01-01T00:00:00Z"}',
  webhook: '{"forge_smoke": true, "event": "ping"}',
};

export function planSmokeTest(args: {
  spec: AgentSpec;
  plan: BuildPlan;
}): SmokePlan {
  const { spec, plan } = args;
  const input = SYNTHETIC_INPUTS[spec.trigger];
  const entrypoint = plan.target.entrypoint;

  return {
    driverContent: buildSmokeDriver({
      entrypoint,
      trigger: spec.trigger,
    }),
    command: 'npx tsx --tsconfig tsconfig.json forge_smoke.mjs',
    stdin: spec.trigger === 'chat' ? input : undefined,
    // For server-like triggers we don't expect a clean exit; the module is
    // considered loaded after a short delay with no error output.
    softTimeout: spec.trigger === 'api' || spec.trigger === 'webhook',
    timeoutMs: spec.trigger === 'api' || spec.trigger === 'webhook' ? 15_000 : 25_000,
  };
}

function buildSmokeDriver(args: {
  entrypoint: string;
  trigger: AgentSpec['trigger'];
}): string {
  const input = JSON.stringify(SYNTHETIC_INPUTS[args.trigger]);
  const entrypoint = JSON.stringify('./' + args.entrypoint);
  return [
    "// Generated by Aurexis Forge sandbox runner. Loads the agent and",
    "// exercises it with a synthetic safe input. Tools are in mock mode",
    "// (FORGE_MOCK_TOOLS=1), so no real network calls happen.",
    "",
    "const TRIGGER = " + JSON.stringify(args.trigger) + ";",
    "const SYNTHETIC_INPUT = " + input + ";",
    "const ENTRYPOINT = " + entrypoint + ";",
    "",
    "function log(tag, payload) {",
    "  const line = '[smoke] ' + tag + (payload ? ' ' + JSON.stringify(payload) : '');",
    "  console.log(line);",
    "}",
    "",
    "async function tryImport(path) {",
    "  try {",
    "    const mod = await import(path);",
    "    return { ok: true, mod };",
    "  } catch (err) {",
    "    return { ok: false, error: err && err.message ? err.message : String(err) };",
    "  }",
    "}",
    "",
    "function findAgent(mod) {",
    "  if (!mod || typeof mod !== 'object') return null;",
    "  const candidates = [mod.default, mod.agent, mod.AGENT];",
    "  for (const c of candidates) {",
    "    if (c && typeof c === 'object' && typeof c.handler === 'function') return c;",
    "  }",
    "  return null;",
    "}",
    "",
    "async function main() {",
    "  const candidates = [ENTRYPOINT, './src/agent.ts', './src/agent.js'];",
    "  let mod = null;",
    "  let loadedPath = null;",
    "  const importErrors = [];",
    "  for (const cand of candidates) {",
    "    const res = await tryImport(cand);",
    "    if (res.ok) {",
    "      mod = res.mod;",
    "      loadedPath = cand;",
    "      break;",
    "    }",
    "    importErrors.push(cand + ': ' + res.error);",
    "  }",
    "  if (!mod) {",
    "    log('module_load_failed', { errors: importErrors });",
    "    process.exit(2);",
    "  }",
    "  log('module_loaded', { path: loadedPath });",
    "",
    "  const agent = findAgent(mod);",
    "  if (!agent) {",
    "    log('no_agent_export', { exports: Object.keys(mod) });",
    "    // Module loaded without errors — that's a soft pass.",
    "    process.exit(0);",
    "  }",
    "",
    "  const runtime = await tryImport('./src/lib/runtime.js');",
    "  if (!runtime.ok || typeof runtime.mod.runOnce !== 'function') {",
    "    log('runtime_missing', { error: runtime.ok ? 'no runOnce' : runtime.error });",
    "    process.exit(3);",
    "  }",
    "",
    "  let parsedInput;",
    "  try {",
    "    parsedInput = JSON.parse(SYNTHETIC_INPUT);",
    "  } catch {",
    "    parsedInput = SYNTHETIC_INPUT;",
    "  }",
    "",
    "  try {",
    "    const result = await runtime.mod.runOnce(agent, parsedInput);",
    "    log('agent_invoked', { result_preview: JSON.stringify(result).slice(0, 400) });",
    "    process.exit(0);",
    "  } catch (err) {",
    "    log('agent_threw', { error: err && err.message ? err.message : String(err) });",
    "    process.exit(4);",
    "  }",
    "}",
    "",
    "main().catch((err) => {",
    "  log('driver_threw', { error: err && err.message ? err.message : String(err) });",
    "  process.exit(99);",
    "});",
    "",
  ].join('\n');
}
