// Aurexis Forge — Phase 3 (Software) deterministic scaffold.
//
// The Next.js + Supabase project skeleton the software codegen
// pipeline materialises BEFORE any LLM call. Every file here is
// data — the codegen layer NEVER executes it (same security boundary
// as Phases 1 + 2).
//
// THREE STRUCTURAL NON-NEGOTIABLES live in this file:
//
//   1. NO HAND-ROLLED AUTH — the sign-in page, the auth callback,
//      the session middleware, and the supabase client wiring all
//      live HERE, not in any LLM-filled slot. The slot-kind dispatch
//      in slots.ts routes every auth slot back to these template
//      files; no LLM call ever produces an auth alternative.
//
//   2. SERVER/CLIENT BOUNDARY — `lib/supabase/server.ts` is
//      server-only and uses the cookie-based session client from
//      @supabase/ssr; `lib/supabase/browser.ts` is client-only and
//      uses ONLY the anon key. Neither references SUPABASE_SERVICE_
//      ROLE_KEY. LLM-filled slots see only these two clients in
//      their prompt context — there is no code path for the LLM to
//      reach for the service-role key.
//
//   3. RLS — the per-entity migration is emitted by migration.ts
//      (RLS policies always on); the scaffold's `supabase/migrations`
//      directory carries only template-wide bootstrap, not entity
//      schema. The codegen assembler combines both.

export interface ScaffoldFile {
  readonly path: string;
  readonly content: string;
}

// ---------------------------------------------------------------------------
// package.json — pinned deps. Only what an authed CRUD app needs:
// next, react, supabase (ssr cookie client + js), typescript types.
// No tool library, no agent runtime — software apps are not agents.
// ---------------------------------------------------------------------------

const PACKAGE_JSON = `{
  "name": "forge-software-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {
    "next": "14.2.15",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "@supabase/ssr": "^0.5.2",
    "@supabase/supabase-js": "^2.45.4"
  },
  "devDependencies": {
    "@types/node": "^20.16.10",
    "@types/react": "^18.3.11",
    "@types/react-dom": "^18.3.0",
    "typescript": "^5.6.2"
  }
}
`;

const TSCONFIG_JSON = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "preserve",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "incremental": true,
    "forceConsistentCasingInFileNames": true,
    "noUncheckedIndexedAccess": true,
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "plugins": [{ "name": "next" }],
    "baseUrl": ".",
    "paths": { "@/*": ["./*"] }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
`;

const NEXT_CONFIG_JS = `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};
module.exports = nextConfig;
`;

// .env.example DECLARES the service-role key for documentation only.
// The generated code never imports it (no admin slot exists yet),
// and the README spells out the boundary so reviewers don't move
// it into a client module by accident.
const ENV_EXAMPLE = `# --- Required ---
NEXT_PUBLIC_SUPABASE_URL=https://YOUR-PROJECT.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=YOUR-ANON-KEY

# --- Optional, SERVER-ONLY ---
# The service-role key bypasses RLS. The generated app DOES NOT use it
# in any module. If you add an admin route later, import it via
# process.env in a SERVER-ONLY file (app/api/**/route.ts). NEVER expose
# it to the browser bundle.
SUPABASE_SERVICE_ROLE_KEY=
`;

const README_MD = `# forge-software-app

Generated by **Aurexis Forge** from a confirmed SoftwareSpec and an
approved SoftwareBuildPlan. The project structure, Supabase client
wiring, Supabase Auth integration, session middleware, and the RLS-
enabled schema migration are deterministic scaffold output. Per-entity
API handlers and per-page UI components are LLM-filled within the
template's slots.

## Layout

- \`app/\` — Next.js App Router. Auth pages live at \`/sign-in\`; the
  authenticated app lives under \`/(app)/\`.
- \`lib/supabase/\` — server + browser Supabase clients. The server
  client uses the cookie-based session from \`@supabase/ssr\`; the
  browser client uses ONLY the anon key.
- \`middleware.ts\` — session refresh + redirect-to-sign-in.
- \`supabase/migrations/\` — schema + RLS policies (one file per phase).

## Three structural non-negotiables

1. **No hand-rolled auth.** Auth is Supabase Auth (magic-link) wired
   through the template's sign-in page + middleware. The Forge's
   codegen pipeline never lets an LLM produce an alternative auth
   mechanism.
2. **RLS on by default.** Every entity table has row-level-security
   enabled with owner-scoped policies. Multi-tenant isolation lives at
   the database, not in app code.
3. **Server/client boundary.** The service-role key is SERVER-ONLY
   and not referenced by any generated module. The browser bundle
   sees only the anon key behind RLS.
`;

// ---------------------------------------------------------------------------
// lib/supabase/server.ts — server-only Supabase client. Uses the
// cookie-based session client from @supabase/ssr so RLS policies
// scope every query to the authenticated user. NEVER touches the
// service-role key.
// ---------------------------------------------------------------------------

const LIB_SUPABASE_SERVER_TS = `// SERVER-ONLY Supabase client. Reads NEXT_PUBLIC_SUPABASE_URL +
// NEXT_PUBLIC_SUPABASE_ANON_KEY and binds them to the request cookie
// store so every query is scoped to the authenticated user under RLS.
//
// This file MUST NOT be imported into a client module. The
// service-role key is NEVER imported here — even though it would
// bypass RLS, it has no use-case in user-facing pages or routes.

import { createServerClient as createSupabaseServer } from '@supabase/ssr';
import { cookies } from 'next/headers';

export function createServerClient() {
  const cookieStore = cookies();
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL ?? '';
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '';
  if (!url || !anonKey) {
    throw new Error(
      'Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY'
    );
  }
  return createSupabaseServer(url, anonKey, {
    cookies: {
      get(name: string) {
        return cookieStore.get(name)?.value;
      },
      set(name: string, value: string, options) {
        try {
          cookieStore.set({ name, value, ...options });
        } catch {
          // Server Components cannot set cookies; the middleware refreshes
          // the session, so a failure here is non-fatal for read paths.
        }
      },
      remove(name: string, options) {
        try {
          cookieStore.set({ name, value: '', ...options });
        } catch {
          // see above
        }
      },
    },
  });
}
`;

// ---------------------------------------------------------------------------
// lib/supabase/browser.ts — client-only Supabase client. Uses the
// anon key ONLY. RLS policies in the database constrain what this
// client can read or write.
// ---------------------------------------------------------------------------

const LIB_SUPABASE_BROWSER_TS = `'use client';

// CLIENT-ONLY Supabase client. Reads NEXT_PUBLIC_SUPABASE_URL +
// NEXT_PUBLIC_SUPABASE_ANON_KEY (both public values bundled into the
// browser). RLS in the database is the only thing standing between
// this client and another user's rows.
//
// This file MUST NOT reference SUPABASE_SERVICE_ROLE_KEY. The
// codegen pipeline never authors a client module that does.

import { createBrowserClient as createSupabaseBrowser } from '@supabase/ssr';

export function createBrowserClient() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL ?? '';
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '';
  return createSupabaseBrowser(url, anonKey);
}
`;

// ---------------------------------------------------------------------------
// middleware.ts — refresh the Supabase session on every request and
// redirect un-authed users to /sign-in. This is the SESSION_MIDDLEWARE
// slot the planner declares; the LLM never re-authors it.
// ---------------------------------------------------------------------------

const MIDDLEWARE_TS = `// Aurexis Forge — Supabase session middleware (template-emitted).
//
// Refreshes the Supabase auth cookie on every request and redirects
// un-authed users to /sign-in for any route under /(app)/. The
// codegen pipeline NEVER lets an LLM rewrite this file — the file is
// the canonical Supabase Auth slot.

import { createServerClient } from '@supabase/ssr';
import { NextResponse, type NextRequest } from 'next/server';

export async function middleware(req: NextRequest) {
  const res = NextResponse.next({ request: { headers: req.headers } });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL ?? '',
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? '',
    {
      cookies: {
        get(name) {
          return req.cookies.get(name)?.value;
        },
        set(name, value, options) {
          res.cookies.set({ name, value, ...options });
        },
        remove(name, options) {
          res.cookies.set({ name, value: '', ...options });
        },
      },
    },
  );

  const { data } = await supabase.auth.getUser();
  const isAuthRoute =
    req.nextUrl.pathname.startsWith('/sign-in') ||
    req.nextUrl.pathname.startsWith('/auth/');
  if (!data.user && !isAuthRoute) {
    const url = req.nextUrl.clone();
    url.pathname = '/sign-in';
    return NextResponse.redirect(url);
  }
  return res;
}

export const config = {
  // Match every route except static assets and the Next.js internals.
  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)'],
};
`;

// ---------------------------------------------------------------------------
// app/sign-in/page.tsx — the SIGN-IN slot. Client component that
// posts to a server action to send a magic link. Never authored by
// the LLM.
// ---------------------------------------------------------------------------

const APP_SIGN_IN_PAGE_TSX = `'use client';

// Aurexis Forge — Supabase Auth sign-in page (template-emitted).
// Uses the BROWSER Supabase client and the standard magic-link flow.
// The codegen pipeline NEVER lets an LLM rewrite this file.

import { useState, type FormEvent } from 'react';
import { createBrowserClient } from '@/lib/supabase/browser';

export default function SignInPage() {
  const [email, setEmail] = useState('');
  const [status, setStatus] = useState<'idle' | 'sending' | 'sent' | 'error'>(
    'idle',
  );
  const [error, setError] = useState<string | null>(null);

  async function onSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setStatus('sending');
    setError(null);
    const supabase = createBrowserClient();
    const { error: err } = await supabase.auth.signInWithOtp({
      email: email.trim(),
      options: {
        emailRedirectTo:
          (typeof window !== 'undefined' ? window.location.origin : '') +
          '/auth/callback',
      },
    });
    if (err) {
      setStatus('error');
      setError(err.message);
      return;
    }
    setStatus('sent');
  }

  return (
    <main style={{ maxWidth: 420, margin: '4rem auto', padding: '1rem' }}>
      <h1>Sign in</h1>
      <p>We&apos;ll email you a magic link.</p>
      <form onSubmit={onSubmit}>
        <input
          type="email"
          required
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          placeholder="you@example.com"
          style={{ width: '100%', padding: '0.5rem', marginTop: '1rem' }}
        />
        <button
          type="submit"
          disabled={status === 'sending' || status === 'sent'}
          style={{ marginTop: '1rem', padding: '0.5rem 1rem' }}
        >
          {status === 'sending' ? 'Sending…' : status === 'sent' ? 'Check your inbox' : 'Send magic link'}
        </button>
      </form>
      {error ? <p style={{ color: 'crimson', marginTop: '1rem' }}>{error}</p> : null}
    </main>
  );
}
`;

// ---------------------------------------------------------------------------
// app/auth/callback/route.ts — handles the magic-link redirect,
// completes the session, and routes to /. Template-emitted.
// ---------------------------------------------------------------------------

const APP_AUTH_CALLBACK_ROUTE_TS = `// Aurexis Forge — Supabase Auth callback (template-emitted).
// Completes the magic-link sign-in by exchanging the OTP code for a
// session cookie, then redirects to the app root.

import { NextResponse, type NextRequest } from 'next/server';
import { createServerClient } from '@/lib/supabase/server';

export async function GET(req: NextRequest) {
  const url = new URL(req.url);
  const code = url.searchParams.get('code');
  if (code) {
    const supabase = createServerClient();
    await supabase.auth.exchangeCodeForSession(code);
  }
  return NextResponse.redirect(new URL('/', req.url));
}
`;

// ---------------------------------------------------------------------------
// app/layout.tsx — root layout. Minimal; the per-app shell can be
// styled later. Template-emitted.
// ---------------------------------------------------------------------------

const APP_LAYOUT_TSX = `// Aurexis Forge — root layout (template-emitted).
import type { ReactNode } from 'react';

export const metadata = {
  title: 'Forged app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          fontFamily:
            'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, sans-serif',
        }}
      >
        {children}
      </body>
    </html>
  );
}
`;

// ---------------------------------------------------------------------------
// lib/auth/roles.ts — the ROLE_GATE slot. Deterministic helper the
// generated pages call to check the current user's role. Never
// LLM-authored.
// ---------------------------------------------------------------------------

const LIB_AUTH_ROLES_TS = `// Aurexis Forge — role gate (template-emitted).
//
// Reads the current user's role from the JWT's app_metadata.role
// claim and returns true when it's in the allowed set. Generated
// pages call this on the server BEFORE rendering protected content.

import { createServerClient } from '@/lib/supabase/server';

export async function userHasAnyRole(allowed: string[]): Promise<boolean> {
  if (allowed.length === 0) return true;
  const supabase = createServerClient();
  const { data } = await supabase.auth.getUser();
  const role = (data.user?.app_metadata?.role as string | undefined) ?? null;
  return role !== null && allowed.includes(role);
}

export async function currentUserId(): Promise<string | null> {
  const supabase = createServerClient();
  const { data } = await supabase.auth.getUser();
  return data.user?.id ?? null;
}
`;

// ---------------------------------------------------------------------------
// lib/auth/rls.ts — the PER_USER_ISOLATION_CHECK slot. Documents
// which entities have per-user RLS. Never LLM-authored.
// ---------------------------------------------------------------------------

function libAuthRlsTs(entityNames: ReadonlyArray<string>, perUserIsolation: boolean): string {
  return [
    "// Aurexis Forge — per-user isolation declaration (template-emitted).",
    "//",
    "// This file documents the entities whose tables carry per-user RLS",
    "// policies. The actual enforcement lives in the schema migration",
    "// (supabase/migrations/0001_init.sql) — this file is a build-time",
    "// artefact so reviewers can grep for the contract in one place.",
    "",
    'export const PER_USER_ISOLATION = ' + String(perUserIsolation) + ';',
    "",
    'export const ISOLATED_ENTITIES: readonly string[] = [' +
      entityNames.map((n) => JSON.stringify(n)).join(', ') +
      '] as const;',
    "",
  ].join('\n');
}

// ---------------------------------------------------------------------------
// Scaffold assembly. Returns the deterministic file set the codegen
// pipeline materialises BEFORE any LLM call. Auth files are ALWAYS
// here — the slot dispatch in slots.ts routes auth slot kinds back
// to these canonical files instead of invoking the LLM.
// ---------------------------------------------------------------------------

export interface ScaffoldArgs {
  // Used by the auth file to enumerate entities (per_user_isolation_check
  // slot's deterministic emit). Not used to alter ANY other file.
  entityNames: ReadonlyArray<string>;
  perUserIsolation: boolean;
}

export function resolveSoftwareScaffold(args: ScaffoldArgs): ScaffoldFile[] {
  return [
    { path: 'package.json', content: PACKAGE_JSON },
    { path: 'tsconfig.json', content: TSCONFIG_JSON },
    { path: 'next.config.js', content: NEXT_CONFIG_JS },
    { path: '.env.example', content: ENV_EXAMPLE },
    { path: 'README.md', content: README_MD },
    { path: 'lib/supabase/server.ts', content: LIB_SUPABASE_SERVER_TS },
    { path: 'lib/supabase/browser.ts', content: LIB_SUPABASE_BROWSER_TS },
    { path: 'lib/auth/roles.ts', content: LIB_AUTH_ROLES_TS },
    {
      path: 'lib/auth/rls.ts',
      content: libAuthRlsTs(args.entityNames, args.perUserIsolation),
    },
    { path: 'middleware.ts', content: MIDDLEWARE_TS },
    { path: 'app/layout.tsx', content: APP_LAYOUT_TSX },
    { path: 'app/sign-in/page.tsx', content: APP_SIGN_IN_PAGE_TSX },
    { path: 'app/auth/callback/route.ts', content: APP_AUTH_CALLBACK_ROUTE_TS },
  ];
}

// The set of file paths the scaffold ALWAYS materialises. The slot
// dispatch in slots.ts checks against this set to verify auth slots
// resolve to template-emitted paths and to refuse any LLM-filled slot
// that would overwrite a template file.
export const SCAFFOLD_PATHS: ReadonlySet<string> = new Set([
  'package.json',
  'tsconfig.json',
  'next.config.js',
  '.env.example',
  'README.md',
  'lib/supabase/server.ts',
  'lib/supabase/browser.ts',
  'lib/auth/roles.ts',
  'lib/auth/rls.ts',
  'middleware.ts',
  'app/layout.tsx',
  'app/sign-in/page.tsx',
  'app/auth/callback/route.ts',
]);

// The compact summary of the scaffold's public surface the LLM
// consumes when filling an API route or a page component. Carries
// the EXACT import paths an LLM-filled slot must reach for — never
// the service-role key, never an alternative client. Bounded so the
// per-slot prompt stays small.
export const SCAFFOLD_INTERFACE = `// lib/supabase/server.ts
export function createServerClient(): SupabaseClient;
//   - Server-only. RLS is enforced by the database.
//   - Use this in app/(app)/**/page.tsx (server components) AND in
//     every app/api/**/route.ts. Never import lib/supabase/browser
//     from a server file; never import lib/supabase/server from a
//     'use client' file.

// lib/auth/roles.ts
export function userHasAnyRole(allowed: string[]): Promise<boolean>;
export function currentUserId(): Promise<string | null>;
//   - Server-only helpers. Call userHasAnyRole(['admin']) at the top
//     of a protected page or route.

// SUPABASE_SERVICE_ROLE_KEY is intentionally NOT exposed in any
// helper. The generated app has no admin slot in this phase.
`;
