// Aurexis Forge — Phase 2 (Systems) runtime live-driver synthesis.
//
// The runtime executor writes ONE extra file into the live sandbox —
// `forge_system_live.mjs` — that imports the generated orchestrator
// and runs ONE end-to-end orchestration in LIVE mode. Same shape as
// the system sandbox SMOKE driver (lib/engine/system/sandbox/smoke.ts)
// but live: tools are NOT mocked, real env vars are injected, real
// network calls happen.
//
// The orchestrator's two non-negotiables are still enforced:
//   - MAX-STEPS ceiling: the generated orchestrator embeds the literal
//     from SystemSpec.max_steps; a runaway throws before steps can
//     exceed it.
//   - HANDOFF VALIDATION: any module that drops a declared output is
//     caught by the orchestrator's fail-closed check and surfaces as
//     an OrchestratorError — the executor records the failing node.

import type { OrchestrationPlan } from '../planner/schema';

export interface SystemLiveRunPlan {
  // Contents of forge_system_live.mjs to write into the sandbox.
  driverContent: string;
  // The shell command the executor runs for the live phase.
  command: string;
  // Hard wall-clock cap (inherits from runtime.max_run_ms upstream).
  // No softTimeout — a live system run that doesn't return is a fail.
  timeoutMs: number;
  // The external input we synthesise. For the live driver we keep the
  // same shape as smoke (a string placeholder per from===null handoff
  // key) UNLESS a future runtime accepts a real trigger payload.
  externalInput: Record<string, unknown>;
}

// loop_with_break wiring — when present, the driver additionally extracts
// the controller's decision signal + the body terminal output from the
// orchestrate() result so the bounded-loop runtime can decide whether to
// run another iteration and what to thread into it. Absent for every
// other pattern (the driver emits the same markers as before).
export interface SystemLiveRunLoopHooks {
  // Node id whose output carries the { decision, reason } control signal.
  controllerId: string;
  // Node id whose output is threaded into the NEXT iteration's body entry.
  backEdgeFrom: string;
}

const DEFAULT_LIVE_TIMEOUT_MS = 60_000;

// Build the synthetic external input the live orchestrator sees on
// each tick. Walks the plan's `from===null` handoffs and produces a
// placeholder string per declared output key. The runtime trigger
// (cron tick / manual run-now) doesn't carry a payload in V1 — when
// it does, this is the seam to widen.
export function buildLiveExternalInput(
  plan: OrchestrationPlan,
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const node of plan.nodes) {
    for (const h of node.inputs) {
      if (h.from === null) {
        out[h.output] = '<tick:' + h.output + '>';
      }
    }
  }
  return out;
}

export function planSystemLiveRun(args: {
  plan: OrchestrationPlan;
  maxRunMs?: number;
  // Optional explicit external input — used by the bounded-loop runtime to
  // thread the previous iteration's body output into the next iteration.
  // When omitted, the synthetic tick placeholders are used (today's shape).
  externalInput?: Record<string, unknown>;
  // Optional loop wiring (loop_with_break only).
  loop?: SystemLiveRunLoopHooks;
}): SystemLiveRunPlan {
  const externalInput = args.externalInput ?? buildLiveExternalInput(args.plan);
  const expectedSteps = args.plan.nodes.length;
  const finalNode =
    args.plan.execution_order[args.plan.execution_order.length - 1] ?? '';

  return {
    driverContent: buildLiveDriver({
      externalInput,
      expectedSteps,
      finalNode,
      loop: args.loop ?? null,
    }),
    command: 'npx tsx --tsconfig tsconfig.json forge_system_live.mjs',
    timeoutMs: args.maxRunMs ?? DEFAULT_LIVE_TIMEOUT_MS,
    externalInput,
  };
}

function buildLiveDriver(args: {
  externalInput: Record<string, unknown>;
  expectedSteps: number;
  finalNode: string;
  loop: SystemLiveRunLoopHooks | null;
}): string {
  const externalInputJson = JSON.stringify(args.externalInput);
  const controllerIdJson = JSON.stringify(args.loop?.controllerId ?? null);
  const backEdgeFromJson = JSON.stringify(args.loop?.backEdgeFrom ?? null);
  return [
    "// Generated by Aurexis Forge — Phase 2 system runtime live driver.",
    "// Loads the generated orchestrator and runs ONE end-to-end orchestration",
    "// in LIVE mode. Real env vars + real network calls. Prints a structured",
    "// [run] line on every terminal state — the executor parses these to",
    "// build the run row.",
    "",
    "const EXTERNAL_INPUT = " + externalInputJson + ";",
    "const EXPECTED_STEPS = " + String(args.expectedSteps) + ";",
    "const EXPECTED_FINAL_NODE = " + JSON.stringify(args.finalNode) + ";",
    "// loop_with_break wiring (null for every other pattern).",
    "const LOOP_CONTROLLER_ID = " + controllerIdJson + ";",
    "const LOOP_BACK_EDGE_FROM = " + backEdgeFromJson + ";",
    "",
    "function log(tag, payload) {",
    "  const line = '[run] ' + tag + (payload ? ' ' + JSON.stringify(payload) : '');",
    "  console.log(line);",
    "}",
    "",
    "async function main() {",
    "  let orchestratorMod;",
    "  try {",
    "    orchestratorMod = await import('./src/orchestrator.ts');",
    "  } catch (err) {",
    "    log('orchestrator_load_failed', {",
    "      error: err && err.message ? err.message : String(err),",
    "    });",
    "    process.exit(2);",
    "    return;",
    "  }",
    "",
    "  if (typeof orchestratorMod.orchestrate !== 'function') {",
    "    log('orchestrator_missing_export', { exports: Object.keys(orchestratorMod) });",
    "    process.exit(3);",
    "    return;",
    "  }",
    "",
    "  try {",
    "    const result = await orchestratorMod.orchestrate(EXTERNAL_INPUT);",
    "    if (!result || typeof result !== 'object') {",
    "      log('bad_result_shape', { got: typeof result });",
    "      process.exit(5);",
    "      return;",
    "    }",
    "    // loop_with_break: surface the controller's decision + the body",
    "    // terminal output so the bounded-loop runtime can decide whether to",
    "    // run another iteration and what to thread into it. Null otherwise.",
    "    const outs = result.outputs && typeof result.outputs === 'object' ? result.outputs : {};",
    "    const controllerOut = LOOP_CONTROLLER_ID && outs[LOOP_CONTROLLER_ID] ? outs[LOOP_CONTROLLER_ID] : null;",
    "    const rawDecision = controllerOut && typeof controllerOut === 'object' ? controllerOut.decision : null;",
    "    const decision = rawDecision === 'break' || rawDecision === 'continue' ? rawDecision : null;",
    "    const decisionReason = controllerOut && typeof controllerOut === 'object' && typeof controllerOut.reason === 'string' ? controllerOut.reason : null;",
    "    const finalOutput = LOOP_BACK_EDGE_FROM && outs[LOOP_BACK_EDGE_FROM] ? outs[LOOP_BACK_EDGE_FROM] : null;",
    "    log('orchestrate_passed', {",
    "      steps: result.steps,",
    "      final_node: result.final_node,",
    "      expected_steps: EXPECTED_STEPS,",
    "      expected_final_node: EXPECTED_FINAL_NODE,",
    "      output_keys: result.outputs ? Object.keys(result.outputs) : [],",
    "      decision: decision,",
    "      decision_reason: decisionReason,",
    "      final_output: finalOutput,",
    "    });",
    "    process.exit(0);",
    "  } catch (err) {",
    "    if (err && err.name === 'OrchestratorError') {",
    "      log('orchestrate_failed', {",
    "        node: err.node === undefined ? null : err.node,",
    "        message: err.message,",
    "      });",
    "      process.exit(1);",
    "      return;",
    "    }",
    "    log('orchestrator_threw', {",
    "      error: err && err.message ? err.message : String(err),",
    "      name: err && err.name ? err.name : 'unknown',",
    "    });",
    "    process.exit(4);",
    "  }",
    "}",
    "",
    "main().catch((err) => {",
    "  log('driver_threw', { error: err && err.message ? err.message : String(err) });",
    "  process.exit(99);",
    "});",
    "",
  ].join('\n');
}

// Parse the orchestrator result the live driver emits on success.
// Returns null when the stdout doesn't carry a parseable success line
// (the executor then marks the run failed). Mirrors the smoke
// parser's posture but reads the LIVE marker.
export interface LiveRunResult {
  steps: number;
  final_node: string;
  output_keys: string[];
  // loop_with_break only — null/absent for every other pattern.
  decision: 'continue' | 'break' | null;
  decision_reason: string | null;
  final_output: Record<string, unknown> | null;
}

export function parseLiveRunResult(combined: string): LiveRunResult | null {
  const lines = combined.split('\n');
  for (let i = lines.length - 1; i >= 0; i--) {
    const line = lines[i];
    if (!line) continue;
    const marker = '[run] orchestrate_passed ';
    const at = line.indexOf(marker);
    if (at < 0) continue;
    const jsonStr = line.slice(at + marker.length).trim();
    try {
      const parsed = JSON.parse(jsonStr) as unknown;
      if (
        parsed &&
        typeof parsed === 'object' &&
        'steps' in parsed &&
        'final_node' in parsed
      ) {
        const p = parsed as {
          steps: number;
          final_node: string;
          output_keys?: string[];
          decision?: unknown;
          decision_reason?: unknown;
          final_output?: unknown;
        };
        const decision =
          p.decision === 'break' || p.decision === 'continue' ? p.decision : null;
        return {
          steps: p.steps,
          final_node: p.final_node,
          output_keys: Array.isArray(p.output_keys) ? p.output_keys : [],
          decision,
          decision_reason:
            typeof p.decision_reason === 'string' ? p.decision_reason : null,
          final_output:
            p.final_output && typeof p.final_output === 'object' && !Array.isArray(p.final_output)
              ? (p.final_output as Record<string, unknown>)
              : null,
        };
      }
    } catch {
      // Fall through and keep searching.
    }
  }
  return null;
}

// Parse the orchestrator failure line. Same shape as the smoke
// version but reads the LIVE marker.
export function parseLiveRunFailure(
  combined: string,
): { node: string | null; message: string } | null {
  const lines = combined.split('\n');
  for (let i = lines.length - 1; i >= 0; i--) {
    const line = lines[i];
    if (!line) continue;
    const marker = '[run] orchestrate_failed ';
    const at = line.indexOf(marker);
    if (at < 0) continue;
    const jsonStr = line.slice(at + marker.length).trim();
    try {
      const parsed = JSON.parse(jsonStr) as unknown;
      if (parsed && typeof parsed === 'object') {
        const p = parsed as { node?: string | null; message?: string };
        return {
          node: typeof p.node === 'string' ? p.node : null,
          message: typeof p.message === 'string' ? p.message : '',
        };
      }
    } catch {
      // Fall through.
    }
  }
  return null;
}
