// Aurexis Forge — Phase 2 (Systems) runtime live-driver synthesis.
//
// The runtime executor writes ONE extra file into the live sandbox —
// `forge_system_live.mjs` — that imports the generated orchestrator
// and runs ONE end-to-end orchestration in LIVE mode. Same shape as
// the system sandbox SMOKE driver (lib/engine/system/sandbox/smoke.ts)
// but live: tools are NOT mocked, real env vars are injected, real
// network calls happen.
//
// The orchestrator's two non-negotiables are still enforced:
//   - MAX-STEPS ceiling: the generated orchestrator embeds the literal
//     from SystemSpec.max_steps; a runaway throws before steps can
//     exceed it.
//   - HANDOFF VALIDATION: any module that drops a declared output is
//     caught by the orchestrator's fail-closed check and surfaces as
//     an OrchestratorError — the executor records the failing node.

import type { OrchestrationPlan } from '../planner/schema';

export interface SystemLiveRunPlan {
  // Contents of forge_system_live.mjs to write into the sandbox.
  driverContent: string;
  // The shell command the executor runs for the live phase.
  command: string;
  // Hard wall-clock cap (inherits from runtime.max_run_ms upstream).
  // No softTimeout — a live system run that doesn't return is a fail.
  timeoutMs: number;
  // The external input we synthesise. For the live driver we keep the
  // same shape as smoke (a string placeholder per from===null handoff
  // key) UNLESS a future runtime accepts a real trigger payload.
  externalInput: Record<string, string>;
}

const DEFAULT_LIVE_TIMEOUT_MS = 60_000;

// Build the synthetic external input the live orchestrator sees on
// each tick. Walks the plan's `from===null` handoffs and produces a
// placeholder string per declared output key. The runtime trigger
// (cron tick / manual run-now) doesn't carry a payload in V1 — when
// it does, this is the seam to widen.
export function buildLiveExternalInput(
  plan: OrchestrationPlan,
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const node of plan.nodes) {
    for (const h of node.inputs) {
      if (h.from === null) {
        out[h.output] = '<tick:' + h.output + '>';
      }
    }
  }
  return out;
}

export function planSystemLiveRun(args: {
  plan: OrchestrationPlan;
  maxRunMs?: number;
}): SystemLiveRunPlan {
  const externalInput = buildLiveExternalInput(args.plan);
  const expectedSteps = args.plan.nodes.length;
  const finalNode =
    args.plan.execution_order[args.plan.execution_order.length - 1] ?? '';

  return {
    driverContent: buildLiveDriver({
      externalInput,
      expectedSteps,
      finalNode,
    }),
    command: 'npx tsx --tsconfig tsconfig.json forge_system_live.mjs',
    timeoutMs: args.maxRunMs ?? DEFAULT_LIVE_TIMEOUT_MS,
    externalInput,
  };
}

function buildLiveDriver(args: {
  externalInput: Record<string, string>;
  expectedSteps: number;
  finalNode: string;
}): string {
  const externalInputJson = JSON.stringify(args.externalInput);
  return [
    "// Generated by Aurexis Forge — Phase 2 system runtime live driver.",
    "// Loads the generated orchestrator and runs ONE end-to-end orchestration",
    "// in LIVE mode. Real env vars + real network calls. Prints a structured",
    "// [run] line on every terminal state — the executor parses these to",
    "// build the run row.",
    "",
    "const EXTERNAL_INPUT = " + externalInputJson + ";",
    "const EXPECTED_STEPS = " + String(args.expectedSteps) + ";",
    "const EXPECTED_FINAL_NODE = " + JSON.stringify(args.finalNode) + ";",
    "",
    "function log(tag, payload) {",
    "  const line = '[run] ' + tag + (payload ? ' ' + JSON.stringify(payload) : '');",
    "  console.log(line);",
    "}",
    "",
    "async function main() {",
    "  let orchestratorMod;",
    "  try {",
    "    orchestratorMod = await import('./src/orchestrator.ts');",
    "  } catch (err) {",
    "    log('orchestrator_load_failed', {",
    "      error: err && err.message ? err.message : String(err),",
    "    });",
    "    process.exit(2);",
    "    return;",
    "  }",
    "",
    "  if (typeof orchestratorMod.orchestrate !== 'function') {",
    "    log('orchestrator_missing_export', { exports: Object.keys(orchestratorMod) });",
    "    process.exit(3);",
    "    return;",
    "  }",
    "",
    "  try {",
    "    const result = await orchestratorMod.orchestrate(EXTERNAL_INPUT);",
    "    if (!result || typeof result !== 'object') {",
    "      log('bad_result_shape', { got: typeof result });",
    "      process.exit(5);",
    "      return;",
    "    }",
    "    log('orchestrate_passed', {",
    "      steps: result.steps,",
    "      final_node: result.final_node,",
    "      expected_steps: EXPECTED_STEPS,",
    "      expected_final_node: EXPECTED_FINAL_NODE,",
    "      output_keys: result.outputs ? Object.keys(result.outputs) : [],",
    "    });",
    "    process.exit(0);",
    "  } catch (err) {",
    "    if (err && err.name === 'OrchestratorError') {",
    "      log('orchestrate_failed', {",
    "        node: err.node === undefined ? null : err.node,",
    "        message: err.message,",
    "      });",
    "      process.exit(1);",
    "      return;",
    "    }",
    "    log('orchestrator_threw', {",
    "      error: err && err.message ? err.message : String(err),",
    "      name: err && err.name ? err.name : 'unknown',",
    "    });",
    "    process.exit(4);",
    "  }",
    "}",
    "",
    "main().catch((err) => {",
    "  log('driver_threw', { error: err && err.message ? err.message : String(err) });",
    "  process.exit(99);",
    "});",
    "",
  ].join('\n');
}

// Parse the orchestrator result the live driver emits on success.
// Returns null when the stdout doesn't carry a parseable success line
// (the executor then marks the run failed). Mirrors the smoke
// parser's posture but reads the LIVE marker.
export function parseLiveRunResult(
  combined: string,
): { steps: number; final_node: string; output_keys: string[] } | null {
  const lines = combined.split('\n');
  for (let i = lines.length - 1; i >= 0; i--) {
    const line = lines[i];
    if (!line) continue;
    const marker = '[run] orchestrate_passed ';
    const at = line.indexOf(marker);
    if (at < 0) continue;
    const jsonStr = line.slice(at + marker.length).trim();
    try {
      const parsed = JSON.parse(jsonStr) as unknown;
      if (
        parsed &&
        typeof parsed === 'object' &&
        'steps' in parsed &&
        'final_node' in parsed
      ) {
        const p = parsed as {
          steps: number;
          final_node: string;
          output_keys?: string[];
        };
        return {
          steps: p.steps,
          final_node: p.final_node,
          output_keys: Array.isArray(p.output_keys) ? p.output_keys : [],
        };
      }
    } catch {
      // Fall through and keep searching.
    }
  }
  return null;
}

// Parse the orchestrator failure line. Same shape as the smoke
// version but reads the LIVE marker.
export function parseLiveRunFailure(
  combined: string,
): { node: string | null; message: string } | null {
  const lines = combined.split('\n');
  for (let i = lines.length - 1; i >= 0; i--) {
    const line = lines[i];
    if (!line) continue;
    const marker = '[run] orchestrate_failed ';
    const at = line.indexOf(marker);
    if (at < 0) continue;
    const jsonStr = line.slice(at + marker.length).trim();
    try {
      const parsed = JSON.parse(jsonStr) as unknown;
      if (parsed && typeof parsed === 'object') {
        const p = parsed as { node?: string | null; message?: string };
        return {
          node: typeof p.node === 'string' ? p.node : null,
          message: typeof p.message === 'string' ? p.message : '',
        };
      }
    } catch {
      // Fall through.
    }
  }
  return null;
}
